bounswe/bounswe2024group1

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/PR_TEMPLATE/pull_request_template.md

Related issue: #7 
- Created issue template.
- Created pull request template.
Please comment if you have any improvements.

Issue & PR Templates

---

.github/ISSUE_TEMPLATE/issue_tracker.md

Create issue tracker template

---

backend/Dockerfile
backend/docker-compose.yaml
backend/pom.xml
backend/src/main/java/com/group1/cuisines/CuisinesApplication.java
backend/src/main/java/com/group1/cuisines/controllers/SearchController.java
backend/src/main/java/com/group1/cuisines/entities/Dish.java
backend/src/main/java/com/group1/cuisines/entities/User.java
backend/src/main/java/com/group1/cuisines/services/WikidataService.java
backend/src/main/resources/application-docker.properties
backend/src/main/resources/application.properties
backend/src/main/resources/banner.txt
backend/src/test/java/com/group1/cuisines/AuthenticationControllerTest.java

Related issue: [#81 ](https://github.com/bounswe/bounswe2024group1/issues/81)
- Search Controller implemented.
- WikidataService and filtering based on search parameter implemented
Reviewer : @mmtftr

Wikidata Api Search Route for dishes and service implementation

---

backend/Dockerfile
backend/docker-compose.yaml
backend/src/main/java/com/group1/cuisines/entities/User.java
backend/src/main/resources/application-docker.properties
backend/src/main/resources/application.properties
backend/src/test/java/com/group1/cuisines/AuthenticationControllerTest.java

Related issue: [#76 ](https://github.com/bounswe/bounswe2024group1/issues/76)
- Dockefile implemented.
- docker-compose.yaml implemented.
- application-docker.properties implemented
Reviewer : @atakanyasar

Dockerize backend

---

backend/README.md

Related issue: [#88 ](https://github.com/bounswe/bounswe2024group1/issues/88)
- Requirements to build and run backend app
- Instructions for local and dockerized environment.
- Warnings about some common issues and resources for maven commands.

Write Readme backend instructions

---

frontend/package.json
frontend/src/components/ui/card.tsx
frontend/src/components/ui/input.tsx
frontend/src/components/ui/label.tsx
frontend/src/index.css
frontend/src/routes/index.tsx
frontend/src/routes/login.tsx
frontend/src/routes/signup.tsx
frontend/yarn.lock

Frontend/feature/91 signup login UI

---

frontend/src/App.test.tsx
frontend/src/routes/login.test.tsx
frontend/src/routes/login.tsx
frontend/tests/setup.ts

- Added test coverage for this behavior
- Changed UI labels

Accept usernames in login

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java

Frontend team can access user-infos for authenticated user  through sending jwt token.

users/me endpoint implemented.

---

backend/pom.xml
backend/src/main/java/com/group1/cuisines/entities/Bookmark.java
backend/src/main/java/com/group1/cuisines/entities/Comment.java
backend/src/main/java/com/group1/cuisines/entities/Cuisine.java
backend/src/main/java/com/group1/cuisines/entities/Dish.java
backend/src/main/java/com/group1/cuisines/entities/Ingredient.java
backend/src/main/java/com/group1/cuisines/entities/Rating.java
backend/src/main/java/com/group1/cuisines/entities/Recipe.java
backend/src/main/java/com/group1/cuisines/entities/Upvote.java
backend/src/main/java/com/group1/cuisines/repositories/BookmarkRepository.java
backend/src/main/java/com/group1/cuisines/repositories/CommentRepository.java
backend/src/main/java/com/group1/cuisines/repositories/CuisineRepository.java
backend/src/main/java/com/group1/cuisines/repositories/DishRepository.java
backend/src/main/java/com/group1/cuisines/repositories/IngredientsRepository.java
backend/src/main/java/com/group1/cuisines/repositories/RatingRepository.java
backend/src/main/java/com/group1/cuisines/repositories/RecipeRepository.java
backend/src/main/java/com/group1/cuisines/repositories/UpvoteRepository.java
backend/src/main/java/com/group1/cuisines/services/WikidataService.java
backend/src/main/resources/application.properties
backend/src/main/resources/banner.txt

Entity classes are created & mappings between those entities handled

Entity classes are created & mappings between those entities handled

---

backend/src/main/java/com/group1/cuisines/StartupRunner.java
backend/src/main/java/com/group1/cuisines/controllers/SearchController.java
backend/src/main/java/com/group1/cuisines/entities/Cuisine.java
backend/src/main/java/com/group1/cuisines/entities/Dish.java
backend/src/main/java/com/group1/cuisines/repositories/DishRepository.java
backend/src/main/java/com/group1/cuisines/services/SearchService.java
backend/src/main/java/com/group1/cuisines/services/WikidataService.java

Search service rearranged and storage mechanism established.

 Implement storage mechanism wikidata

---

backend/src/main/java/com/group1/cuisines/controllers/CuisineController.java
backend/src/main/java/com/group1/cuisines/entities/Cuisine.java
backend/src/main/java/com/group1/cuisines/services/CuisineService.java

Implemented /cuisines/{cuisineId} endpoint

Implemented /cuisines/{cuisineId} endpoint

---

backend/src/main/java/com/group1/cuisines/controllers/SearchController.java
backend/src/main/java/com/group1/cuisines/controllers/UserController.java
backend/src/main/java/com/group1/cuisines/entities/User.java
backend/src/main/java/com/group1/cuisines/repositories/UserRepository.java
backend/src/main/java/com/group1/cuisines/services/UserService.java
backend/src/main/resources/application.properties

Implemented search/users endpoint

Implemented search/users endpoint

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java
backend/src/main/java/com/group1/cuisines/entities/User.java
backend/src/main/java/com/group1/cuisines/repositories/UserRepository.java
backend/src/main/java/com/group1/cuisines/services/UserService.java
backend/src/main/resources/application.properties

/users/follow endpoint implemented.

/users/follow endpoint implemented.

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java
backend/src/main/java/com/group1/cuisines/services/UserService.java

Implemented /users/unfollow implemented and tested.

/users/unfollow endpoint implemented.

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java

/follow & /unfollow endpoints now take Path variable (userId)

/follow & /unfollow endpoints now take Path variable (userId)

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java
backend/src/main/java/com/group1/cuisines/dto/UserDto.java
backend/src/main/java/com/group1/cuisines/services/UserService.java

"/{userId}/following" endpoint implemented & UserDto class defined and used for response.

"/{userId}/following" endpoint implemented.

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java
backend/src/main/java/com/group1/cuisines/services/UserService.java

"/{userId}/followers" endpoint implemented.

"/{userId}/followers" endpoint implemented.

---

backend/src/main/java/com/group1/cuisines/controllers/RecipeController.java
backend/src/main/java/com/group1/cuisines/dto/IngredientsDto.java
backend/src/main/java/com/group1/cuisines/dto/NewRecipeDto.java
backend/src/main/java/com/group1/cuisines/dto/RecipeDetailDto.java
backend/src/main/java/com/group1/cuisines/entities/Recipe.java
backend/src/main/java/com/group1/cuisines/repositories/DishRepository.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java

POST "/recipes" endpoint implemented which allows user to create a recipe.

POST "/recipes" endpoint implemented.

---

backend/src/main/java/com/group1/cuisines/config/SecurityConfiguration.java
backend/src/main/java/com/group1/cuisines/controllers/RecipeController.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java
backend/src/main/resources/application.properties

DELETE "/recipes" endpoint implemented. A user can delete recipes created previously.

DELETE "/recipes" endpoint implemented.

---

backend/src/main/java/com/group1/cuisines/controllers/RecipeController.java
backend/src/main/java/com/group1/cuisines/dto/RatingDto.java
backend/src/main/java/com/group1/cuisines/entities/Recipe.java
backend/src/main/java/com/group1/cuisines/repositories/RatingRepository.java
backend/src/main/java/com/group1/cuisines/repositories/RecipeRepository.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java

Implemented POST "recipes/{recipe_id} rating endpoint & small changes in Recipy entity class for ensuring mapping between rating and recipe.

Implemented POST "recipes/{recipe_id} rating endpoint 

---

backend/src/main/java/com/group1/cuisines/controllers/RecipeController.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java

- Get who bookmarked the recipe.

GET /recipes/{recipeId}/bookmarks endpoint implemented

---

.github/workflows/frontend.yml
backend/src/main/resources/application.properties

Add github actions to frontend

add frontend github actions

---

backend/src/main/java/com/group1/cuisines/controllers/RecipeController.java
backend/src/main/java/com/group1/cuisines/dto/RecipeDto.java
backend/src/main/java/com/group1/cuisines/entities/Cuisine.java
backend/src/main/java/com/group1/cuisines/entities/Dish.java
backend/src/main/java/com/group1/cuisines/entities/Recipe.java
backend/src/main/java/com/group1/cuisines/repositories/RecipeRepository.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java
backend/src/main/resources/application.properties

Implemented GET /recipes endpoint.

Implemented GET /recipes endpoint .

---

backend/src/main/java/com/group1/cuisines/config/SecurityConfiguration.java
backend/src/main/java/com/group1/cuisines/controllers/FeedController.java
backend/src/main/java/com/group1/cuisines/entities/User.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java

GET /feed endpoint implemented

GET /feed endpoint implemented

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java
backend/src/main/java/com/group1/cuisines/dao/response/ErrorResponse.java
backend/src/main/java/com/group1/cuisines/dto/BookmarkDto.java
backend/src/main/java/com/group1/cuisines/dto/UserProfileDto.java
backend/src/main/java/com/group1/cuisines/entities/User.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java
backend/src/main/java/com/group1/cuisines/services/UserService.java

GET users/{userId} endpoint implemented.

GET users/{userId} endpoint implemented.

---

backend/src/main/java/com/group1/cuisines/repositories/DishRepository.java

Adjusted the query to search other fields
Resolves #213

feat(backend): adjust query to search other fields

---

backend/src/main/java/com/group1/cuisines/dto/AuthorDto.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java
backend/src/main/java/com/group1/cuisines/services/UserService.java

GET /users/{userId} response format reimplemented.

 Format GET /users/{userId} response reimplemented.

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java

Format GET /users/{userId}/following response

Format GET /users/{userId}/following response

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java

Format GET /users/follow and /users/unfollow response.

Format GET /users/follow and /users/unfollow response.

---

backend/src/main/java/com/group1/cuisines/controllers/SearchController.java

Format GET /search/users response.

Format GET /search/users response.

---

backend/src/main/java/com/group1/cuisines/controllers/FeedController.java

Format response for /feed .

---

.github/workflows/backend_test.yml
.github/workflows/frontend_test.yml

Removed PR triggers on develop and made the file filters finer on the push trigger.
Resolves #215

chore(devops): remove redundant trigger

---

frontend/src/components/Recipe.tsx
frontend/src/routes/feed.tsx
frontend/src/routes/home.tsx
frontend/src/services/api/semanticBrowseComponents.ts
swagger/openapi.yml

Some linting errors were introduced in a previous PR. This PR fixes the linting errors

fix(frontend): linting errors

---

backend/src/main/java/com/group1/cuisines/controllers/SearchController.java
backend/src/main/java/com/group1/cuisines/controllers/UserController.java
backend/src/main/java/com/group1/cuisines/dto/UserDto.java
backend/src/main/java/com/group1/cuisines/dto/UserProfileDto.java
backend/src/main/java/com/group1/cuisines/services/UserService.java

Format response for /follow /unfollow  endpoints (isFollowing field)

Format response for /follow /unfollow  endpoints (isFollowing field)

---

backend/src/main/java/com/group1/cuisines/controllers/RecipeController.java
backend/src/main/java/com/group1/cuisines/controllers/UserController.java

feat(backend): detailed my profile page

---

backend/src/main/java/com/group1/cuisines/dto/IngredientsDto.java
backend/src/main/java/com/group1/cuisines/entities/Ingredient.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java
backend/src/main/java/com/group1/cuisines/services/UserService.java

feat(backend): add amount of ingredients

---

backend/src/test/java/com/group1/cuisines/UserControllerTest.java

Add user controller unit tests

add user controller unit tests

---

frontend/package.json
frontend/src/components/BookmarkButton.tsx
frontend/src/components/Recipe.tsx
frontend/src/routes/recipe.tsx
frontend/src/services/auth.tsx

- Created bookmark button with normal and icon variant
- Integrated API mutations with the button
- Integrated Copy Link functionality to recipe card and page.

feat(frontend): implement bookmark functionality

---

frontend/package.json
frontend/src/components/BookmarkButton.tsx
frontend/yarn.lock

- Removed condition for testing
- Removed cypress (unused dependency)

fix(frontend): remove unused dep, incorrect check (Quick fix)

---

frontend/src/App.tsx
frontend/src/components/BookmarkButton.tsx
frontend/src/components/Profile.tsx
frontend/src/routes/index.tsx
frontend/src/routes/recipe.tsx
frontend/src/services/query-client.ts

- Added more profile picture placeholders
- Added authentication checks to not show buttons that require authentication
- Added comments section into the Recipe page

fix(frontend): add more authentication checks

---

backend/src/main/java/com/group1/cuisines/controllers/RecipeController.java
backend/src/main/java/com/group1/cuisines/dto/CommentsDto.java
backend/src/main/java/com/group1/cuisines/dto/NewCommentDto.java
backend/src/main/java/com/group1/cuisines/entities/Comment.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java

Format responses for POST /comment

Format responses for POST /comment

---

backend/src/main/java/com/group1/cuisines/dto/DishDto.java
backend/src/main/java/com/group1/cuisines/entities/Recipe.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java
backend/src/main/java/com/group1/cuisines/services/UserService.java

- make dishes nullable while creating recipe.

fix(backend): make dishes nullable

---

frontend/src/components/BookmarkButton.tsx
frontend/src/components/Dish.tsx
frontend/src/components/Recipe.tsx
frontend/src/routes/create-recipe.tsx
frontend/src/routes/search.tsx

- Added plus recipe button
- Fixed allergens usage
- Made buttons closer on Recipe Card.

feat(frontend): implement plus recipe button

---

backend/src/main/java/com/group1/cuisines/controllers/RecipeController.java
backend/src/main/java/com/group1/cuisines/dto/UpvoteDto.java
backend/src/main/java/com/group1/cuisines/entities/Bookmark.java
backend/src/main/java/com/group1/cuisines/entities/Comment.java
backend/src/main/java/com/group1/cuisines/entities/Cuisine.java
backend/src/main/java/com/group1/cuisines/entities/Dish.java
backend/src/main/java/com/group1/cuisines/entities/Ingredient.java
backend/src/main/java/com/group1/cuisines/entities/Rating.java
backend/src/main/java/com/group1/cuisines/entities/Recipe.java
backend/src/main/java/com/group1/cuisines/entities/Upvote.java
backend/src/main/java/com/group1/cuisines/entities/User.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java

Format response for post /recipes/{recipe id}/comments/{comment id}/upvote endpoint

 Format response for post /recipes/{recipe id}/comments/{comment id}/upvote endpoint 

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java
backend/src/main/java/com/group1/cuisines/dto/UserProfileDto.java
backend/src/main/java/com/group1/cuisines/dto/UserUpdateFormDto.java
backend/src/main/java/com/group1/cuisines/entities/User.java
backend/src/main/java/com/group1/cuisines/services/UserService.java

Users should be able to update their profile by put /users/{userId}.

feat(backend): update profile details

---

frontend/src/components/Dish.tsx
frontend/src/services/api/semanticBrowseContext.ts

Added authentication barrier to recipe create
Fixed incorrect usage of useAuthStore inside the API context

fix(frontend): incorrect usage of auth store

---

backend/src/test/java/com/group1/cuisines/DishControllerTest.java

- Test when GetDishById is found.
- Test when GetDishById is not found.

feat(backend): test dish controller

---

frontend/package.json
frontend/src/components/Bookmarkers.test.tsx

created a basic unit test for bookmarkers

added unit test for bookmarkers

---

frontend/src/components/BookmarkButton.test.tsx
frontend/src/components/BookmarkButton.tsx
frontend/src/components/Recipe.tsx
frontend/src/routes/create-recipe.tsx
frontend/src/routes/dish.tsx
frontend/src/routes/profile.tsx
frontend/src/services/api/semanticBrowseSchemas.ts
frontend/src/services/query-client.ts
swagger/openapi.yml

- Fixed edge cases
- Added more validation and authentication checks before showing items
- Changed unauthenticated error message
- Made headers and labels link to their respective entities (dish/recipe)
- Wrote 4 unit tests for bookmarkbutton
- Disabled edit profile as there are bugs with the backend

Frontend/fix Some quick fixes

---

.github/workflows/backend_deploy_staging.yml

fix(devops): setup doctl

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/design.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/implement_feature.md
.github/ISSUE_TEMPLATE/issue_tracker.md
.github/PR_TEMPLATE/pull_request_template.md

- Got rid of unused titles.
- Feature Request
- Added new issue types
- Implement a Feauture
- Design
- Documentation

Create issue templates

---

frontend/src/services/api/programmingForumComponents.ts
frontend/src/services/api/programmingForumResponses.ts
frontend/src/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- Created API Schema
- Regenerated frontend code
Closes #348

Create API schema and update frontend API code

---

backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Requests/SigninRequestDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Requests/SignupRequestDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GenericApiResponse.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/SigninResponse.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/SignupResponse.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/User.java

- The request & response DTOs are implemented for authentication requests & responses
Closes #386

Implemented generic request & response DTOs for authentication.

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/SecurityConfiguration.java
backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/AuthenticationController.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/BaseController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/ErrorResponse.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GenericApiResponse.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/SigninResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/SignupResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/User.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/AuthenticationService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/JwtService.java

- The signup endpoint  and service implemented.
Closes #385

Implement signup flow.

---

backend/pom.xml
backend/src/main/java/com/group1/programminglanguagesforum/Config/JwtAuthenticationFilter.java
backend/src/main/java/com/group1/programminglanguagesforum/Config/ModelMapperConfig.java
backend/src/main/java/com/group1/programminglanguagesforum/Config/SecurityConfiguration.java
backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/UserController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/SelfProfileResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/User.java
backend/src/main/java/com/group1/programminglanguagesforum/Exceptions/CustomAccessDeniedHandler.java
backend/src/main/java/com/group1/programminglanguagesforum/Exceptions/CustomAuthenticationEntryPoint.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/JwtService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserContextService.java
backend/src/main/resources/application.properties

- Implemented user/me endpoint & also cached some exceptions thrown by not controller but filter.
Closes #391

Implemented user/me endpoint & also catching some exceptions thrown by secutiy

---

archive/frontend/src/routes/recipe.tsx
archive/swagger/openapi.yml
frontend/package.json
frontend/src/App.tsx
frontend/src/components/ErrorAlert.tsx
frontend/src/components/ErrorBoundary.tsx
frontend/src/components/FollowButton.tsx
frontend/src/components/NavbarLayout.tsx
frontend/src/routes/index.tsx
frontend/src/routes/question.test.tsx
frontend/src/routes/question.tsx
frontend/src/services/api/programmingForumComponents.ts
frontend/src/services/api/programmingForumResponses.ts
frontend/src/services/api/programmingForumSchemas.ts
frontend/src/services/auth.tsx
frontend/yarn.lock
swagger/openapi.yml

- The question page design is implemented as in the UI design and allows the user to view, bookmark, delete questions.
Closes #363

Create Question Page

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/ModelMapperConfig.java
backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/UserController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/UserProfileResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Exceptions/CustomAccessDeniedHandler.java
backend/src/main/java/com/group1/programminglanguagesforum/Exceptions/CustomAuthenticationEntryPoint.java
backend/src/main/java/com/group1/programminglanguagesforum/Exceptions/UnauthorizedAccessException.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/AuthenticationService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserContextService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserService.java
backend/src/main/java/com/group1/programminglanguagesforum/Util/ApiResponseBuilder.java

- users/{userId} GET implemented
Closes #395

Implemented users/{userId} GET endpoint

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/SecurityConfiguration.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/UserController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Requests/UserProfileUpdateRequestDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Exceptions/UserNotFoundException.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserService.java

- Implemented PUT users/{userId} 
Closes #396

Implemented users/{userId} PUT endpoint

---

backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/UserController.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/User.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserService.java

- Implemented users/{userId}/follow POST endpoint
Closes #397

Implemented users/{userId}/follow POST endpoint

---

frontend/src/components/AnswerItem.tsx
frontend/src/components/Answers.test.tsx
frontend/src/components/Answers.tsx
frontend/src/components/NavbarLayout.tsx
frontend/src/routes/question.test.tsx
frontend/src/routes/question.tsx
frontend/src/services/api/programmingForumComponents.ts
frontend/src/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- The answers section inside the question page is rendered as in the Figma design.
Closes #365

[FE] Implement Answer View

---

backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/UserController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/UserSummaryDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserService.java

- Users can get followers of an account.
Closes #408

[BE] Feature/408 get followers

---

.do/app-prod.yml
backend/src/main/resources/application-docker.properties
mobile/eas.json
mobile/package.json

[Release] Do another test release

---

.github/workflows/backend_test.yml

- Silenced dependency fetch, enabled batch mode

[Devops] Shortened Backend Tests CI output

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/UserController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/UserProfileResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserService.java

selfFollowing feature is added
Closes #425

[BE] Feature/425 self following

---

backend/src/main/java/com/group1/programminglanguagesforum/Entities/Question.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/User.java

- Question entity implemented.
Closes #436

Question entity.

---

backend/src/main/java/com/group1/programminglanguagesforum/Entities/Answer.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Question.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/User.java

- Answer entity created.
Closes #438

Answer Entity Created.

---

backend/pom.xml
backend/src/main/java/com/group1/programminglanguagesforum/Constants/CodeExecutionConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/CodeExecutionController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Requests/CodeExecutionRequestDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/CodeExecutionResponseDTO.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/CodeExecutionService.java

- Code execution API
Closes #439

[BE] feat(backend): implement code execution service

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/VoteController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/QuestionDownvoteResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/VoteService.java

- POST question downvote endpoint implemented.
Closes #449

Backend/feature/449 implement POST question Downvote

---

backend/pom.xml
backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Constants/GeneralConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/ProgrammingLanguagesTag.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/WikidataService.java

- Wikidata service is implemented.
Closes #455

Backend Wikidata Service Impl

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/ModelMapperConfig.java
backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/TagController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetProgrammingLanguageTagResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetProgrammingParadigmResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetTagDetailsResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/TagType.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/TagService.java

- Endpoint for retrieving specific tag implemented.
Closes #457 
---
---
---

GET tags/{tagId} endpoint

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/QuestionController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Requests/CreateQuestionRequestDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/AuthorDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/CreateQuestionResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/TagDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Question.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/User.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/TagRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/JwtService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/TagService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/WikidataService.java

- Create Question endpoint is implemented.
Closes #456

Implement POST /questions

---

backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/BookmarkController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/BookmarkQuestionResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Bookmark.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Question.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/BookmarkRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/BookmarkService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java

- Bookmark endpoint implemented. A registered user can bookmark a question.
Closes #465 
---
---

Implement POST /questions/{questionId}/bookmark

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/TagController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Requests/CreateTagRequestDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Tag.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/TagType.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/TagService.java

- Implemented /tags endpoint to allow registered users to create their own tags with community.
Closes #467

Implement POST /tags. Create new tag .

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/ModelMapperConfig.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Requests/SignupRequestDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Requests/UserProfileUpdateRequestDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetQuestionWithTagDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetTagDetailsResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/UserProfileResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/UserSummaryDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/ExperienceLevel.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/User.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/QuestionRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/AuthenticationService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/TagService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/VoteService.java
frontend/src/components/HighlightedQuestionCard.tsx
frontend/src/components/HighlightedQuestionsBox.tsx
frontend/src/routes/tag.tsx
frontend/src/services/api/programmingForumSchemas.ts
frontend/src/services/temporaryMocks.ts
mobile/app/tags/[tagId].tsx
mobile/components/QuestionCard.tsx
mobile/services/api/programmingForumSchemas.ts
mobile/services/temporaryMocks.ts
swagger/openapi.yml

- [Design] User Story 1 (@Cgtycolak - #489)
- [Design] User Story 2 (@NazireAta - )
- [Frontend] Implement keyboard shortcuts for the mid-level engineer's UX (Cmd/Ctrl+K, / for search bar focus, Cmd/Ctrl+N for new question) (@mmtftr  - #issue)
- [Frontend] Implement experience level field in signup (@mmtftr - #issue)
- [Mobile] Add `Copy to clipboard` button to code snippets box (@mmtftr  - #issue)
- [Frontend] Add `Copy to clipboard` button to code snippets box (@asligook  - #488 )
- [Mobile] Adjust color schema (@atakanyasar - #484)
- [Mobile] Render highlighted questions (@atakanyasar - #483 
- [Backend] Add experienceLevel to user object
- [Backend] Add highlightedQuestions to tag object

[Lab] Lab 6 PR

---

backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/VoteController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/AnswerVoteResponseDTO.java
backend/src/main/java/com/group1/programminglanguagesforum/Exceptions/ExceptionResponseHandler.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/VoteRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/VoteService.java

- Users can vote answers.
- Created ExceptionResponseHandler class for future refactoring for exceptions.
Closes #446 
Closes #447

Implement POST answer/{answerId}/upvote and answer/{answerId}/downvote

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/JwtAuthenticationFilter.java
backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/TagController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/TagSearchResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/TagRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/TagService.java

- Endpoint for tag search implemented.
Closes #523

Search Tag Endpoint implemented.

---

backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/AnswerController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Requests/CreateAnswerRequestDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/CreateAnswerResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Answer.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Question.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/AnswerService.java
backend/src/test/java/com/group1/programminglanguagesforum/Services/TagServiceTests.java

- A registered user can post an answer for a question.
Closes #524

Create answer endpoint implemented.

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/SecurityConfiguration.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/QuestionController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetQuestionDetailsResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/BookmarkRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/BookmarkService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java

- A user can see a question detail.
Closes #526

Get Question Detail endpoint implemented.

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/AnswerController.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/AnswerService.java

- Delete Answer endpoint implemented.
Closes #532

Delete Answer endpoint implemented.

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/AnswerController.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/AnswerService.java

- A registered user can update answer.
Closes #533

Update an answer endpoint implemented.

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/QuestionController.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java

- A user can delete a question.
Closes #538 
-

Delete a question endpoint implemented.

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/QuestionController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Requests/UpdateQuestionRequestDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetQuestionDetailsResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java

- UDATE questions/{questionId} endpoint implemented
Closes #539 
-

Update a question endpoint implemented.

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/JwtAuthenticationFilter.java

- Server now returns 404 for invalid & undefined routes.
Closes #541 
-

404 Not found error fixed.

---

frontend/src/routes/search.tsx
frontend/src/services/api/programmingForumComponents.ts
frontend/src/services/api/programmingForumSchemas.ts
mobile/.expo/types/router.d.ts
mobile/app/(tabs)/_layout.tsx
mobile/app/(tabs)/profile.tsx
mobile/app/(tabs)/search.tsx
mobile/app/question/new.tsx
mobile/components/FullscreenLoading.tsx
mobile/components/TagCard.tsx
mobile/services/api/programmingForumComponents.ts
mobile/services/api/programmingForumFetcher.ts
mobile/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- The profile page is implemented as in the design.
Closes #508

[Mobile] Create Profile Page

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/AnswerController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetAnswersResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/VoteRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/AnswerService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/VoteService.java

- An endpoint implemented to retrieve answers for a question.
Closes #540
-

Get answers for a question endpoint & service implemented.

---

frontend/src/components/ExerciseCard.tsx
frontend/src/routes/question.test.tsx
frontend/src/routes/question.tsx
frontend/src/services/exercism.ts

- Added Exercism API integration
- Fixed linking to Exercism exercises
Closes #548

[Frontend] Added Exercism Recommendations Integration

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/SecurityConfiguration.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/QuestionController.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java
frontend/src/components/CodeSnippet.tsx
frontend/src/components/CreateAnswerForm.test.tsx
frontend/src/components/CreateAnswerForm.tsx
frontend/src/components/ui/badge.tsx
frontend/src/routes/question.test.tsx
frontend/src/routes/question.tsx
frontend/src/routes/tag.tsx

- Implement answer creation form
- (Backend) Fix GET question returning unauthorized for non-logged in users and for not-found questions.
Closes #503 #561

[FE] Implement Answer Create Form

---

frontend/src/components/Tag.tsx
frontend/src/routes/profile.tsx
frontend/src/routes/tag.tsx

[Deploy] Test deployment

---

backend/src/main/java/com/group1/programminglanguagesforum/Services/AnswerService.java
frontend/src/services/exercism.ts

Do another test deploy including some exercism fixes and GET question/:id/answers requiring auth.

[Deploy] Test deploy

---

backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetAnswersResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetQuestionDetailsResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/VoteRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/AnswerService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java

- Users can see their self votes.
Closes #559

feat(backend): add selfVoted for question and answers

---

frontend/src/App.test.tsx
frontend/src/routes/feed.tsx
frontend/src/routes/home.test.tsx
frontend/src/routes/home.tsx
frontend/src/routes/login.test.tsx

- The home page will be shown to all users and it will include tags, latest questions and related exercises.
Closes #571.

[FE] Implement Feed Page

---

backend/pom.xml
backend/src/main/resources/postman_collection/CMPE451-Backend.postman_collection.json
backend/src/main/resources/postman_collection/README.MD

- Document, update if necessary, and specify the acceptance criteria for:
- primary features, (@mmtftr @EnesBaserr) #583 
- domain-specific features (@Cgtycolak @NazireAta ) #584 
- API and its documentation (@EnesBaserr ) #585 
- Testing strategy (@atakanyasar) #587 
- Project Standards (@ozdentarikcan ) #586 
- prepare the Meeting notes for lab8 (@asligook)

[Lab] Lab 8

---

backend/src/main/java/com/group1/programminglanguagesforum/Services/TagService.java

Bugfix for questionCount.

---

frontend/src/components/CreateAnswerForm.test.tsx
frontend/src/components/CreateAnswerForm.tsx

- The documentation popover has been implemented as requested by the customer.
Closes #588

[Frontend] Implement Code Block Popover

---

frontend/src/components/DifficultyFilter.tsx
frontend/src/routes/create-question.tsx
frontend/src/routes/tag.tsx
frontend/src/services/api/programmingForumSchemas.ts
mobile/app/question/new.tsx
mobile/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- The difficulty filter is implemented as needed
- Fixed a tag selection bug in question create page
Closes #600

[Frontend] Add difficulty filter to Tag Page

---

frontend/src/components/QuestionCard.tsx
frontend/src/components/SearchBar.test.tsx
frontend/src/components/SearchBar.tsx
frontend/src/components/SearchQuestionsList.tsx
frontend/src/components/SearchTagsList.tsx
frontend/src/routes/search.tsx
frontend/tests/setup.ts

- The question search page is implemented
Closes #617

[Frontend] Implement Question search

---

frontend/src/components/QuestionCard.tsx
frontend/src/components/SearchBar.test.tsx
frontend/src/components/SearchBar.tsx
frontend/src/components/SearchQuestionsList.tsx
frontend/src/components/SearchTagsList.tsx
frontend/src/routes/feed.tsx
frontend/src/routes/profile.tsx
frontend/src/routes/search.tsx
frontend/src/routes/tag.tsx
frontend/src/services/api/programmingForumSchemas.ts
frontend/tests/setup.ts
mobile/components/QuestionCard.tsx
mobile/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- The question card shows the difficulty level.
- All pages using the question card now pass the difficulty level info to the card component.
Closes #605

[Frontend] Add Difficulty Level in Question Card

---

.github/workflows/frontend_test.yml

- The CI now type-checks frontend
Closes #614 
No automated tests, but manual test will be done to see if the logs contain type-checking in the CI

[Devops] Add Frontend type checking to CI

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/ModelMapperConfig.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetQuestionWithTagDto.java
frontend/src/components/ExerciseCard.tsx
frontend/src/components/HighlightedQuestionCard.tsx
frontend/src/components/HighlightedQuestionsBox.tsx
frontend/src/components/QuestionCard.tsx
frontend/src/components/TagCard.tsx
frontend/src/routes/feed.tsx
frontend/src/routes/profile.tsx
frontend/src/routes/tag.tsx
frontend/src/services/api/programmingForumSchemas.ts
mobile/app/(tabs)/profile.tsx
mobile/app/tags/[tagId].tsx
mobile/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- Change all "questionBody" fields' names to "content"
- Implement ModelMappers for relevant endpoints
Closes #619

[Backend] Fix question DTO field

---

frontend/src/components/DifficultyFilter.tsx
frontend/src/components/SearchQuestionsList.tsx

- The question search page now has a difficulty filtering component
Closes #601

[Frontend] Implement Difficulty Filter in the Question Search Page

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/CodeExecutionController.java

- Fixed code exec. response.
Closes #603

Fix code exec. response

---

backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetQuestionDetailsResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java

- Fix question related endpoints to retrieve difficulty level.
Closes #611

Fix question related endpoints to retrieve difficulty level.

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/ModelMapperConfig.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/UserController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/SelfProfileResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/UserProfileResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/TagRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/TagService.java

- Add followed tags to users' profile responses..
Closes #604

Add followed tags to users' profile responses.

---

dev.yml
frontend/src/routes/question.tsx

Add Code Snippets to Question

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/ModelMapperConfig.java
backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/BookmarkController.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/BookmarkRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/BookmarkService.java
backend/src/test/java/com/group1/programminglanguagesforum/Services/BookmarkServiceTests.java
swagger/openapi.yml

- Get questions that user bookmarked.
- Unit test for getting bookmark.
- Added new api to openapi.yml
Closes #630

[BE] Feature/630 get bookmarked questions

---

frontend/src/components/DifficultyBar.tsx
frontend/src/routes/question.test.tsx
frontend/src/routes/question.tsx
frontend/src/services/api/programmingForumComponents.ts
swagger/openapi.yml

Added the Difficulty Rating Poll and the Difficulty Bar to the Questions, getting the input from the users to determine community voting for the difficulty level of a question.
Closes #606

Add Difficulty Rating to Questions

---

mobile/app/(tabs)/index.tsx
mobile/components/Feed.tsx
mobile/components/QuestionsList.tsx
mobile/components/TagList.tsx

- The home page shows  tags, latest questions with pagination.
Closes #651

[Mobile]  Home Page

---

mobile/app/(tabs)/index.tsx
mobile/app/question/[questionId].tsx
mobile/components/Feed.tsx
mobile/components/QuestionCard.tsx
mobile/components/QuestionsList.tsx
mobile/components/TagList.tsx
mobile/services/api/programmingForumComponents.ts
mobile/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- Beginner Friendly Badge
-  Unanswered Badge
- Clickable profile picture and name
- Title and Content
- Number of votes
- Number of answers
- Difficulty
Closes #663

[Mobile] Design Question Card

---

mobile/app/(tabs)/index.tsx
mobile/app/question/[questionId].tsx
mobile/app/tags/[tagId].tsx
mobile/components/Feed.tsx
mobile/components/QuestionCard.tsx
mobile/components/QuestionsList.tsx
mobile/components/TagList.tsx
mobile/services/api/programmingForumComponents.ts
mobile/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- Questions can be filtered by their difficulty level in tag page
Closes #660

[Mobile] Filter Questions By Difficulty

---

.github/workflows/prod_deploy.yml
README.md

- Migrated DO services to new account to avoid paying.
Closes #622

[DevOps] Migrate DigitalOcean account

---

frontend/src/components/TagFollowButton.tsx
frontend/src/routes/tag.test.tsx
frontend/src/routes/tag.tsx

- Follow/Unfollow button is inserted for Tags.
- Button only shows up when the User is a Registered User.
Closes #596.

[Frontend] Folow/Unfollow Tags

---

frontend/src/components/BookmarkButton.tsx
frontend/src/routes/question.test.tsx
frontend/src/routes/question.tsx

- Implement the bookmark button for questions.
The bookmark button is shown at the top right: 
Closes #595

[Frontend] Implement Bookmark button

---

frontend/src/components/HighlightedQuestionCard.tsx
frontend/src/components/HighlightedQuestionsBox.tsx
frontend/src/routes/profile.tsx
frontend/src/routes/question.test.tsx
frontend/src/routes/question.tsx
frontend/src/routes/tag.tsx
frontend/src/services/api/programmingForumSchemas.ts
swagger/openapi.yml

We want the users to edit their own questions as they wish.
-[ ] change the title
-[ ] change the content
-[ ] change the tags
Closes #641

Implement Question Edit

---

mobile/app/(tabs)/index.tsx
mobile/app/(tabs)/profile.tsx
mobile/app/question/[questionId].tsx
mobile/app/tags/[tagId].tsx
mobile/components/Feed.tsx
mobile/components/FollowTagButton.tsx
mobile/components/FollowUserButton.tsx
mobile/components/Profile.tsx
mobile/components/QuestionCard.tsx
mobile/components/QuestionsList.tsx
mobile/components/TagList.tsx
mobile/services/api/programmingForumComponents.ts
mobile/services/api/programmingForumFetcher.ts
mobile/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- Tags can be followed/unfollowed
- Added rendered for svg images
Closes #650

[Mobile] Follow/Unfollow Tag

---

frontend/src/routes/profile.test.tsx
frontend/src/routes/profile.tsx

- Shows reputation points in profile page.
Closes #592

[Frontend] Show reputation points in profile page

---

mobile/app/question/[questionId].tsx
mobile/app/question/[questionId]/answer.tsx
mobile/app/question/new.tsx
mobile/app/tags/[tagId].tsx
mobile/components/Feed.tsx
mobile/components/QuestionsList.tsx
mobile/services/api/programmingForumComponents.ts
mobile/services/api/programmingForumSchemas.ts

- Sort Questions by recommendation in feed page
- Sort questions by recommendation in tag page
- Add content snippet
- Add preview
Closes #700

[Mobile] Sort Recommended Order

---

backend/src/main/java/com/group1/programminglanguagesforum/Repositories/QuestionDifficultyRateRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionDifficultyRateService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java
frontend/src/components/AnswerCard.tsx
frontend/src/components/AnswerItem.tsx
frontend/src/components/Answers.test.tsx
frontend/src/components/Answers.tsx
frontend/src/components/DifficultyBar.tsx
frontend/src/components/SubtypeCard.tsx
frontend/src/components/TagType.tsx
frontend/src/index.css
frontend/src/routes/home.tsx
frontend/src/routes/question.tsx
mobile/components/QuestionCard.tsx

- Fix issues with difficulty level votes.
- Fix some frontend text overflow problems
- Improve UI/UX for editing questions
- Fix question edit tags selector not using existing tags on init
- Add delete answer button
- Fix accessibility contrast issue in code blocks

[Hotfix] Fix some backend/frontend bugs

---

mobile/app/question/[questionId]/answer.tsx
mobile/app/question/new.tsx
mobile/components/PostingGuide.tsx

- Add Popover for writing guide.
-  Put "Add Code" button for simplify adding code.
- Show preview mode.
Closes #704

Enhance New Question and New Answer Screens
