bounswe/bounswe2024group1

backend/src/main/java/com/group1/cuisines/config/SecurityConfiguration.java

Request matchers defined explicitly so that invalid api routes now return Http 404

Request matchers defined explicitly .

---

frontend/src/services/api/semanticBrowseComponents.ts
frontend/src/services/api/semanticBrowseResponses.ts
frontend/src/services/api/semanticBrowseSchemas.ts
swagger/openapi.yml

This pull request updates the OpenAPI specification to version 1.0.3 to align with the latest requirements. The changes include:
Added `/users/me` endpoint to get the current user's profile
Changed `/users/follow` and `/users/unfollow` to `POST /users/{userId}/follow` and `DELETE /users/{userId}/follow` for better REST semantics
Updated `/users/{userId}` response to include isSelfFollowing boolean
Added `POST /cuisines/{cuisineId}/follow` endpoint to follow a cuisine
Added `GET /recipes/{recipeId}/bookmarks` to get users who bookmarked a recipe
Changed `/recipes/{recipeId}/bookmark` to also support `DELETE` to unbookmark
Added comment endpoints:
`GET /recipes/{recipeId}/comments` to get comments
`POST /recipes/{recipeId}/comments` to add a comment
`POST …

Update OpenAPI spec to v1.0.3 with new endpoints and changes

---

backend/src/main/java/com/group1/cuisines/controllers/RecipeController.java
backend/src/main/java/com/group1/cuisines/repositories/BookmarkRepository.java
backend/src/main/java/com/group1/cuisines/services/RecipeService.java

- Add bookmarking a recipe functionality

POST "/recipes/{recipeId}/bookmarks" endpoint implemented

---

backend/pom.xml
backend/src/main/java/com/group1/cuisines/controllers/AuthenticationController.java
backend/src/main/java/com/group1/cuisines/controllers/SearchController.java
backend/src/main/java/com/group1/cuisines/dto/DishResponseDto.java
backend/src/main/java/com/group1/cuisines/exceptions/GlobalExceptionHandler.java
backend/src/main/java/com/group1/cuisines/exceptions/ResourceNotFoundException.java
backend/src/main/java/com/group1/cuisines/services/AuthenticationService.java
backend/src/main/java/com/group1/cuisines/services/SearchService.java
backend/src/test/java/com/group1/cuisines/AuthenticationControllerTest.java

Formatting responses for /search (dishes)

Formatting responses for /search (dishes)

---

backend/src/main/java/com/group1/cuisines/controllers/CuisineController.java
backend/src/main/java/com/group1/cuisines/controllers/FeedController.java
backend/src/main/java/com/group1/cuisines/controllers/RecipeController.java
backend/src/main/java/com/group1/cuisines/controllers/UserController.java
backend/src/main/java/com/group1/cuisines/dao/response/ErrorResponse.java
backend/src/main/java/com/group1/cuisines/dao/response/SuccessResponse.java

Format response /cuisines/{cuisine id} (Get cuisine details)

Format response /cuisines/{cuisine id} (Get cuisine details)

---

backend/src/main/java/com/group1/cuisines/controllers/UserController.java

Format GET /users/{userI}/followers response

Format GET /users/{userI}/followers response

---

frontend/src/components/SearchBar.tsx
frontend/src/components/SearchFilterPopover.test.tsx
frontend/src/components/SearchFilterPopover.tsx
frontend/src/components/ui/popover.tsx

- Added a Filter popover component for use in the search bar
- Added unit tests that test that set functions are not called without clicking on confirm.
- Added unit tests that confirm that the set functions are called correctly.

feat(frontend): add search filter component

---

compose.yml
dev.yml

Added an s3mock service to both prod and development docker compose setups.
Make sure that you use it with path-style endpoints. This requires extra configuration. More info [here](https://github.com/adobe/S3Mock?tab=readme-ov-file#path-style-vs-domain-style-access)

feat(devops): add mock s3 service

---

frontend/package.json
frontend/src/App.tsx
frontend/src/components/Comment.tsx
frontend/src/components/ui/toast.tsx
frontend/src/components/ui/toaster.tsx
frontend/src/components/ui/use-toast.ts
frontend/src/services/api/semanticBrowseFetcher.ts
frontend/src/services/auth.tsx
frontend/src/services/query-client.ts
frontend/yarn.lock

- Added shadcn toast
- Added onError handler to QueryCLient
- Set retries to 1 to avoid long retry times.
- Handled 401 to logout gracefully and redirect to /login with an attached from parameter

feat(frontend): handle errors and show toast

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/JwtAuthenticationFilter.java
backend/src/main/java/com/group1/programminglanguagesforum/Config/SecurityConfiguration.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/AuthenticationController.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/AuthenticationService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/CustomUserDetailsService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/JwtService.java

- A registered user can signin through correect email or username & password.
Closes #387

Implemented signin flow.

---

backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/UserController.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserService.java

- Implemented users/{userId}/unfollow DELETE endpoint
Closes #398

Implemented users/{userId}/unfollow DELETE endpoint

---

.do/app-prod.yml
.github/workflows/validate_pr.yml
backend/src/main/resources/application-docker.properties
compose.yml
mobile/eas.json
mobile/package.json

[Release] Pre-release

---

backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/VoteController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/QuestionUpvoteResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Answer.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Question.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Vote.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/AnswerRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/QuestionRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/TagRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/VoteRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/VoteService.java

- POST questions/{questionId}/upvote is implemented..
Closes #448

Implemented POST question upvote functionality.

---

backend/src/main/java/com/group1/programminglanguagesforum/Services/WikidataService.java

Wrote the SPARQL queries to retrieve data for Programming Languages and Programming Paradigms
The queries were tested in Wikidata Query Service to retrieve the necessary information for both entities.
Closes #444

Backend/feature/444 Create SPARQL Queries

---

backend/src/main/java/com/group1/programminglanguagesforum/Constants/GeneralConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/ComputerScienceTermTag.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/SoftwareLibraryTag.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/WikidataService.java

Wrote the SPARQL queries to retrieve data for Software Library and Computer Science Term
The queries were tested in Wikidata Query Service to retrieve the necessary information for both entities.
Closes #460 and #461

Create Queries for Software Library and Computer Science Term 

---

backend/src/main/java/com/group1/programminglanguagesforum/Services/JwtService.java
frontend/src/components/HighlightedQuestionCard.tsx
frontend/src/components/HighlightedQuestionsBox.tsx
frontend/src/components/QuestionCard.tsx
frontend/src/components/TagCard.tsx
frontend/src/routes/question.test.tsx
frontend/src/routes/question.tsx
frontend/src/routes/tag.test.tsx
frontend/src/routes/tag.tsx
frontend/src/services/api/programmingForumComponents.ts
frontend/src/services/api/programmingForumFetcher.ts
frontend/src/services/api/programmingForumSchemas.ts
mobile/app/question/[questionId].tsx
mobile/app/tags/[tagId].tsx
mobile/components/QuestionCard.tsx
mobile/services/api/programmingForumComponents.ts
mobile/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- Replaced rating/answerCount fields with likeCount/commentCount throughout frontend and mobile
- Updated schema definitions and API endpoints to match new backend contract
- Refactored vote system to use separate upvote/downvote endpoints
- Fixed tag details to use tagId instead of id
- Updated JWT token expiration to 24 hours
- Fixed question card to handle optional author fields
Closes #511
This PR primarily focuses on aligning the frontend/mobile interfaces with the updated backend API contract. The main changes involve:
1. Field renaming:
- rating -> likeCount
- answerCount -> commentCount
- id -> tagId (for tags)
2. API changes:
- Split rating endpoint into separate upvote/downvote endpoints (schema)
- Updated JWT expiration time for better user experience (backend)
3. UI …

[FE/Mobile] Synchronize API schema

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/VoteController.java
backend/src/main/java/com/group1/programminglanguagesforum/Exceptions/QuestionAlreadyVotedException.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/VoteService.java
backend/src/test/java/com/group1/programminglanguagesforum/Services/VoteServiceTests.java

If question already down/upvoted then up/downvote will result in success.
Double upvote and downvote operation is blocked.
- Double upvote and downvote operation is blocked.
- If question already down/upvoted then up/downvote will result in success.
Closes #547 
-

Double upvote and downvote operation is blocked.

---

backend/src/main/java/com/group1/programminglanguagesforum/Constants/EndpointConstants.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/TagController.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Tag.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/User.java
backend/src/main/java/com/group1/programminglanguagesforum/Exceptions/ExceptionResponseHandler.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/TagService.java
backend/src/test/java/com/group1/programminglanguagesforum/Services/TagServiceTests.java

- Users can follow or unfollow tags.
Closes #527

feat(backend): users can follow/unfollow tags

---

frontend/src/components/CreateTagForm.test.tsx
frontend/src/components/CreateTagForm.tsx
frontend/src/components/CreateTagPage.test.tsx
frontend/src/components/CreateTagPage.tsx
frontend/src/components/NavbarLayout.tsx
frontend/src/components/Tags.tsx
frontend/src/routes/index.tsx

- The tag create page allows user to create a new tag with name and description fields.
- The tags tab displays all tags and allows user to create a new tag from that tab.
Closes #504.

[FE] Implement Tag Create

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/ModelMapperConfig.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/UserController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/GetAnswerDtoForProfile.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/SelfProfileResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/AnswerRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/QuestionRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/AnswerService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java

Closes #598 
```
{
"status": 200,
"message": "User retrieved successfully",
"data": {
"id": 1,
"firstName": "atakan",
"lastName": "atli",
"username": "enes",
"email": "enes@example.com",
"bio": "",
"country": "USA",
"answerCount": 4,
"followersCount": 1,
"followingCount": 0,
"reputationPoints": 0,
"questionCount": 5,
"experienceLevel": "BEGINNER",
"questions": [
{
"id": 1,
"title": "Java Serializer 2 ",
"content": "What is this explain me please ?  2",
"difficulty": null,
"upvoteCount": 0,
"downvoteCount": 0,
"answerCount": 3,
"createdAt": "2024-12-05 00:17:47",
"author": {
"id": 1,
"username": "enes",
"reputationPoints": 0,
"profilePicture": null,
"name": "atakan atli"
},
"tags": [
{
"id": 107,
"name": "Elixir"
},
{
"id": 339,
"name": "Pywikibot"
},
{
"id": 60,
"name": "Object REXX"
}
] …
```

Get Questions and Answers for UserProfile

---

frontend/src/routes/create-question.tsx

Add preview to question

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/BookmarkController.java
backend/src/main/java/com/group1/programminglanguagesforum/Exceptions/ExceptionResponseHandler.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/BookmarkService.java
swagger/openapi.yml

- There cannot be two bookmark entities belong to same user and question
Closes #638

[BE] Fix/638-bookmark

---

backend/src/main/java/com/group1/programminglanguagesforum/Config/ModelMapperConfig.java
backend/src/main/java/com/group1/programminglanguagesforum/Controllers/UserController.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/SelfProfileResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/DTOs/Responses/UserProfileResponseDto.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Answer.java
backend/src/main/java/com/group1/programminglanguagesforum/Entities/Question.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/QuestionRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserService.java

- Implemented reputationPoints flow.
Closes #642 
Calculation will be based on this.
```
public Long calculateReputation(User user) {
List<Question> questions = questionRepository.findByAuthorId(user.getId());
long questionCount = questions.size();
Long questionUpvoteCount = questions.stream().map(Question::getUpvoteCount).reduce(0L, Long::sum);
Long questionDownvoteCount = questions.stream().map(Question::getDownvoteCount).reduce(0L, Long::sum);
List< Answer> answers= answerRepository.findByAnsweredBy(user.getId());
long answerCount =  answers.size();
Long answerUpvoteCount = answers.stream().map(Answer::getUpvoteCount).reduce(0L, Long::sum);
Long answerDownvoteCount = answers.stream().map(Answer::getDownvoteCount).reduce(0L, Long::sum);
return (questionCount * 10 + answerCount * 15 + …
```

Implemented reputationPoints flow.

---

frontend/src/routes/profile.tsx
frontend/src/routes/question.test.tsx
frontend/src/routes/question.tsx
frontend/src/services/api/programmingForumSchemas.ts
mobile/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- The profile page now shows the tags that a User follows.
Closes #602

[Frontend] Followed tags in profile

---

frontend/src/components/AnswerCard.tsx
frontend/src/components/AnswerItem.tsx
frontend/src/components/CodeSnippet.tsx
frontend/src/components/DifficultyBar.tsx
frontend/src/components/DifficultyFilter.tsx
frontend/src/components/ExerciseCard.tsx
frontend/src/components/HighlightedQuestionCard.tsx
frontend/src/components/QuestionCard.tsx
frontend/src/components/Tag.tsx
frontend/src/components/TagCard.tsx
frontend/src/routes/create-question.tsx
frontend/src/routes/feed.tsx
frontend/src/routes/profile.tsx
frontend/src/routes/question.tsx
frontend/src/routes/tag.tsx
mobile/app/question/[questionId].tsx
mobile/components/AnswerCard.tsx
mobile/components/AnswerItem.tsx
mobile/components/QuestionCard.tsx
mobile/components/ui/card/styles.tsx

Guaranteed that the Accessibility score is exactly 100 for the following pages:
Closes #644
checked all the pages manually using Lighthouse

Fix Accessibility Issues

---

frontend/src/components/ContentWithSnippets.tsx
frontend/src/components/CreateAnswerForm.tsx
frontend/src/components/CustomAnchor.tsx

- The custom React Markdown component will allow users to mention tags and questions while creating answers.

[FE] Implement Tag and Question References for Answer Creation

---

frontend/src/components/ContentWithSnippets.tsx
frontend/src/components/CreateAnswerForm.tsx
frontend/src/components/CustomAnchor.tsx
frontend/src/routes/tag.tsx

- The author of the tag (if exists) will be displayed on the tag page.
- The author is displayed with the open book icon on the left.
- For accessibility the icon has sr-only text : `Author of {tag.name} is {tag.author}`
Closes #636.

[FE] Display Author Field in the Tag Page

---

frontend/src/components/CodeSnippet.tsx

- Show the execution time in Code Execution blocks.
Here is an example below: 
Closes #593

[Frontend] Show Execution Time

---

backend/src/main/java/com/group1/programminglanguagesforum/Services/TagService.java
backend/src/test/java/com/group1/programminglanguagesforum/Services/TagServiceTests.java

- The tag details endpoint now returns correct `following` field
Closes #667

[Backend] Fix Self Following Field in Tag Details

---

backend/src/main/java/com/group1/programminglanguagesforum/Services/TagService.java
backend/src/test/java/com/group1/programminglanguagesforum/Services/TagServiceTests.java

- The follower count is returned correctly in getTagDetails and searchTags
Closes #681

[Backend] Fix follower count in Tags

---

frontend/src/components/SubtypeCard.tsx
frontend/src/components/TagType.tsx
frontend/src/routes/glossary.test.tsx
frontend/src/routes/glossary.tsx
frontend/src/routes/index.tsx

- The glossary page displays 4 tag type cards for the tag types within the system, which are :
- Programming Language
- Software Library
- Programming Paradigm
- Computer Science Topic
- Tag type cards include the name, short  description and tag count of the tag type.
- Tag type page includes the name, long description and tags in that tag type category.
- Tag type information within the Tag Card component is turned into link and user is redirected to the related tag type page when clicked on.
Closes #652

[FE] Implement Glossary Page and Tag Type Pages

---

backend/src/main/java/com/group1/programminglanguagesforum/Controllers/QuestionController.java
backend/src/main/java/com/group1/programminglanguagesforum/Repositories/QuestionRepository.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/QuestionService.java
backend/src/main/java/com/group1/programminglanguagesforum/Services/UserService.java
frontend/src/components/SearchBar.tsx
frontend/src/components/SearchQuestionsList.tsx
frontend/src/services/api/programmingForumComponents.ts
frontend/src/services/api/programmingForumSchemas.ts
swagger/openapi.yml

- Questions are sorted according to the Users Followed.
- The questions with Authors that are Followed appear higher than other questions.
Closes #689.

[Backend] Sort Questions by Followed Users

---

frontend/src/components/FullscreenLoading.tsx
frontend/src/components/SearchQuestionsList.tsx
frontend/src/components/SearchTagsList.tsx
frontend/src/components/Tags.tsx
frontend/src/routes/bookmarks.tsx
frontend/src/routes/profile.test.tsx
frontend/src/routes/search.test.tsx
frontend/src/routes/tag.tsx

- Use sr-only text instead of aria labels for non-interactive elements.
- Make loading messages visible.
Closes #609

[Frontend] Use sr-only text

---

frontend/src/components/TagType.tsx

- Add loading screen to TagType Page when scrolling instead of moving back to the top when loading.

[Frontend] Add loading screen to TagType Page

---

frontend/src/routes/profile.tsx
frontend/src/routes/tag.tsx

- Added no Tag followed messge.
- Made Tag images smaller.

[Frontend] UX improvements

---

api-docs/.openapi-generator/FILES
api-docs/Apis/QuestionsApi.md
api-docs/Apis/SearchApi.md
api-docs/Apis/TagsApi.md
api-docs/Models/DifficultyLevelRequestDto.md
api-docs/Models/QuestionDetails.md
api-docs/Models/QuestionRateResponseDto.md
api-docs/Models/QuestionSummary.md
api-docs/Models/TagDetails.md
api-docs/Models/TagSummary.md
api-docs/Models/UserProfile.md
api-docs/Models/getBookmarkedQuestions_200_response.md
api-docs/Models/rateQuestion_200_response.md
api-docs/README.md
frontend/coverage/frontend/src/components/HighlightedQuestionCard.tsx.html
frontend/src/components/AnswerCard.test.tsx
frontend/src/components/CodeSnippet.test.tsx
frontend/src/components/CustomAnchor.test.tsx
frontend/src/components/ExerciseCard.test.tsx
frontend/src/components/SearchQuestionsList.test.tsx
frontend/src/components/Tag.test.tsx
frontend/src/components/Tag.tsx
frontend/src/components/Tags.test.tsx
frontend/src/components/Tags.tsx
frontend/src/routes/create-question.test.tsx
frontend/src/routes/create-question.tsx
frontend/tests/setup.ts
frontend/vitest.config.ts
openapitools.json
swagger/openapi.yml

- Coverage report no longer includes auto generated code and config files
- Frontend tests improved
- API docs updated from latest API schema
1. Tag Component Tests (`Tag.test.tsx`)
- Renders tag information correctly (name, description, logo)
- Shows 'See all questions' link with correct href
- Shows create question link when authenticated
- Hides create question link when not authenticated
- Renders image with correct alt and title attributes
2. Tags Page Tests (`Tags.test.tsx`)
- Renders tags list correctly
- Displays loading state
- Displays error state
- Shows create tag button
- Loads more tags when scrolling
- Handles empty tags list
- Updates search results when query changes
3. CustomAnchor Component Tests (`CustomAnchor.test.tsx`)
- Renders a span when no href is provided
- …

[Devops] Add Frontend Tests, Fix Coverage, Update API Docs
